/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Neuroxones(props) {
  const { nodes, materials } = useGLTF('/models/neuroxones.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.019, 0.055, 0.001]} rotation={[-Math.PI / 2, -1.406, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['full-print-table_1'].geometry}
          material={materials.BlackLeazer}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['full-print-table_2'].geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['full-print-table_3'].geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['full-print-table_4'].geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['full-print-table_5'].geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['full-print-table_6'].geometry}
          material={materials['BlackLeazer.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['full-print-table_7'].geometry}
          material={materials['BlackPlastic.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['full-print-table_8'].geometry}
          material={materials['BlackLeazer.002']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/neuroxones.glb')

export default Neuroxones;